spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useSSL=false&characterEncoding=utf-8
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
#bean加载开关：
#true为加载修饰在该类上的bean，false则不加载相关的bean
tangbaobao.spring.bean.load:
  global-exception: true #全局异常开关
  valid-user: false #用户拦截器开关

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.tangyaya8.mmall.pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

